package org.mycola.hebrewcards.model;

public enum FormEnum {
    ABSOLUTE, ACTIVE, CONSTRUCT, FUTURE, IMPERATIVE, INFINITIVE, PASSIVE, PAST, PRESENT, PRESENT_A, UNDEFINED;
//    ABSOLUTE, CONSTRUCT, UNDEFINED;
}
